manager:
  ip: 127.0.0.1
  port: 0

agents:
  os1_lidar:
    enabled: true
    ip: 127.0.0.1
    port: 30001
  os1_imu:
    enabled: true
    ip: 127.0.0.1
    port: 30002

logging:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    root_handler:
      class: logging.handlers.TimedRotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: logs/manager.log
      when: midnight
      interval: 1
      backupCount: 7
      encoding: utf-8
  root:
    level: DEBUG
    handlers: [root_handler]