#Las secciones y loggers de cada agente, llevan por nombre el mismo nombre de archivo del agente, sin la extesión ".py"
manager_ip: 127.0.0.1

os1_lidar_agent:
  manager_port: 0
  local_port: 30001
  output_file_name: lidar.bin
  hw_connection_retries: 5
  sensor_ip: 192.168.0.20 #IP del lidar
  host_ip: 192.168.0.31 #Ip de la interfaz de red donde se conecta el lidar
os1_imu_agent:
  manager_port: 0
  local_port: 30002
  output_file_name: imu_lidar.csv
  hw_connection_retries: 5
  sensor_ip: 192.168.0.20 #IP del lidar
  host_ip: 192.168.0.31 #Ip de la interfaz de red donde se conecta el lidar
gps_agent:
  manager_port: 0
  local_port: 30003
  output_file_name: gps.csv
  hw_connection_retries: 5
  com_port: /dev/ttyACM0 #/dev/ttyGPS0
  usb_id: 067b:2303
  baudrate: 4800
  simulate: True
camera_agent:
  manager_port: 0
  local_port: 30004
  output_file_name:
  hw_connection_retries: 5
  dev_file: /dev/video0
  period: 1
  resolution: 640x480
imu_agent:
  manager_port: 0
  local_port: 30005
  output_file_name: yost_3space_imu.csv
  hw_connection_retries: 5
  sample_rate: 200 #Hz
  usb_id: 2476:1010
  com_port: /dev/ttyYOST0
logging:
  version: 1
  disable_existing_loggers: True
  formatters:
      simple:
          format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
      os1_lidar_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: logs/os1_lidar.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      os1_imu_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: logs/os1_imu.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      gps_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: logs/gps.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      camera_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: logs/camera.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      root_handler:
        class : logging.NullHandler
  loggers:
      os1_lidar_agent:
        handlers: [os1_lidar_handler]
      os1_imu_agent:
        handlers: [os1_imu_handler]
      gps_agent:
        handlers: [gps_handler]
      camera_agent:
        handlers: [camera_handler]
  root:
      level: DEBUG
      handlers: [root_handler]