#Las secciones y loggers de cada agente, llevan por nombre el mismo nombre de archivo del agente, sin la extesión ".py"
manager_ip: 127.0.0.1

agent_os1_lidar:
  manager_port: 0
  local_port: 30001
  output_file_name: lidar.bin
  hw_connection_retries: 100
  sensor_ip: 192.168.0.18 #IP del lidar
  host_ip: 192.168.0.31 #Ip de la interfaz de red donde se conecta el lidar
agent_os1_imu:
  manager_port: 0
  local_port: 30002
  output_file_name: imu_lidar.csv
  hw_connection_retries: 100
  sensor_ip: 192.168.0.18 #IP del lidar
  host_ip: 192.168.0.31 #Ip de la interfaz de red donde se conecta el lidar
agent_gps:
  manager_port: 0
  local_port: 30003
  output_file_name: gps.csv
  hw_connection_retries: 100
  com_port: /dev/ttyACM0 #/dev/ttyGPS0
  usb_id: 067b:2303
  baudrate: 4800
  simulate: False
agent_camera:
  manager_port: 0
  local_port: 30004
  output_file_name:
  hw_connection_retries: 100
  dev_file: /dev/video0
  period: 1
  resolution: 640x480
agent_imu:
  manager_port: 0
  local_port: 30005
  output_file_name: yost_3space_imu.csv
  hw_connection_retries: 100
  sample_rate: 200 #Hz
  usb_id: 2476:1010
  com_port: /dev/ttyACM2
  buttons:
    bNoButton: 0, 4.99
    bSingleButton: 0, 0
    b<: 3.82, 0.40
    b+: 3.82, 1.46
    b>: 3.82, 0.93
    b-: 1.19, 3.83
    bMute: 3.82, 0.67
    bPickup: 2.76, 3.82
    bGPS: 3.82, 2.51
    bHangup: 2.23, 3.83
    bStop: 1.98, 3.83
    bM: 1.72, 3.83
agent_atmega:
  manager_port: 0
  local_port: 30006
  output_file_name:
  hw_connection_retries: 5
  com_port: /dev/ttyARD0
  baudrate: 115200
agent_inet:
  manager_port: 0
  local_port: 30007
  output_file_name:
  hw_connection_retries: 5
  interface: enp7s0
  ping_ip_1: 200.7.7.3 # 200.7.7.3 es NIC Chile
  ping_ip_2: 8.8.8.8 # 8.8.8.8 DNS de Google
agent_data_copy:
  manager_port: 0
  local_port: 30008
  output_file_name:
  hw_connection_retries: 1000
  usb_mount_path: '/var/run/usbmount'
  sync_every: 20

logging:
  version: 1
  disable_existing_loggers: True
  formatters:
      simple:
          format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
      os1_lidar_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/os1_lidar.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      os1_imu_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/os1_imu.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      gps_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/gps.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      camera_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/camera.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      imu_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/imu.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      atmega_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/imu.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      data_copy_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/data_copy.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      inet_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: ../logs/inet.log
        when: midnight
        interval: 1
        backupCount: 7
        encoding: utf-8
      root_handler:
        class : logging.NullHandler
  loggers:
      agent_os1_lidar:
        handlers: [os1_lidar_handler]
      agent_os1_imu:
        handlers: [os1_imu_handler]
      agent_gps:
        handlers: [gps_handler]
      agent_camera:
        handlers: [camera_handler]
      agent_imu:
        handlers: [imu_handler]
      agent_atmega:
        handlers: [atmega_handler]
      agent_data_copy:
        handlers: [data_copy_handler]
      agent_inet:
        handlers: [inet_handler]
  root:
      level: DEBUG
      handlers: [root_handler]